name: team_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  get: ^4.7.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  iconsax_flutter: ^1.0.1
  flutter_intl_phone_field: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  retrofit_generator: ^9.2.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/categories/
    - assets/images/products/
    - assets/images/